import React from 'react';
import { ShieldAlert, Scale, CheckCircle } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto py-8 space-y-6">
      <div className="space-y-2 border-b border-slate-200/60 pb-6">
        <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight">
          Terms of Service
        </h1>
        <p className="text-xs text-slate-500">
          Last updated: September 2026 • LifeCalc Platform
        </p>
      </div>

      <div className="prose prose-slate text-sm text-slate-600 leading-relaxed space-y-6">
        <div className="bg-amber-50/70 border border-amber-200 rounded-xl p-4 flex items-start gap-3 text-amber-900">
          <ShieldAlert className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
          <div className="space-y-1 text-xs leading-relaxed">
            <strong className="font-semibold block text-sm">Educational & Informational Utility:</strong>
            LifeCalc provides deterministic mathematical calculations for educational and planning estimates. We do not provide chartered financial advice, statutory tax filings, or legal counsel.
          </div>
        </div>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-slate-900">1. Acceptance of Terms</h2>
          <p>
            By accessing and using LifeCalc (the "Service"), you agree to abide by these Terms of Service. If you disagree with any portion of these terms, please discontinue using the platform.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-slate-900">2. Free Use & Calculation Accuracy</h2>
          <p>
            All core calculations and Live Previews are 100% free. While our algorithms strictly model statutory formulas (such as Indian New Tax Regime Section 115BAC slabs, Reducing-balance EMI, and university CGPA scales), you should verify outputs with accredited professionals before committing to loan contracts or statutory tax filings.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-slate-900">3. User Accounts & Fair Use</h2>
          <p>
            Users are responsible for safeguarding their login credentials. LifeCalc reserves the right to rate-limit automated abuse, bot scraping, or denial-of-service traffic to preserve platform availability for all legitimate users.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-slate-900">4. Limitation of Liability</h2>
          <p>
            LifeCalc and its contributors shall not be liable for any direct, indirect, incidental, or financial decisions made based on outputs generated by the platform.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-slate-900">5. Governing Law & Contact</h2>
          <p>
            For legal inquiries or clarifications regarding these terms, please contact us at{' '}
            <code className="text-blue-600 bg-slate-100 px-1 py-0.5 rounded">legal@lifecalc.in</code>.
          </p>
        </section>
      </div>
    </div>
  );
}
